name: MIUI ROM Asset Parser CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Installing requirements
        run: |
          sudo apt install python3 python3-pip axel
          python3 -m pip install -r requirements.txt

      - name: Preparing MIUI build
        run: |
          export MIUI_LATEST_TGZ="$(python3 parser.py)"
          axel -n $(nproc --all) -o miui.tgz $MIUI_LATEST_TGZ > logs.txt
          tar -xzf miui.tgz
          tree

      # soon™
