name: MIUI ROM Asset Parser CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - name: Installing requirements
        run: |
          sudo apt install python3 python3-pip wget
          python3 -m pip install -r requirements.txt

      - name: Preparing MIUI build
        run: |
          python3 parser.py
          #| wget -O miui.tgz
          #tar -xzf miui.tgz

      # soon™
